let x = 5;

// try catch

// try {
//   const x = 5;
//   x = 7;
//   console.log("x: ", x);
// } catch (error) {
//   console.log("catched error: ", error);
// } finally {
//   console.log("finally!");
// }
